# Generated by Django 6.0.3 on 2026-03-20 21:28

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated_at")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Good",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated_at")),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Количество"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Цена",
                    ),
                ),
                ("in_promo", models.BooleanField(default=True, verbose_name="Участвует в акциях")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods",
                        to="orders.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated_at")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Общая сумма",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.CreateModel(
            name="OrderGood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated_at")),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "price_at_order",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Цена на момент заказа",
                    ),
                ),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_goods",
                        to="orders.good",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_goods",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в заказе",
                "verbose_name_plural": "Товары в заказе",
                "unique_together": {("order", "good")},
            },
        ),
        migrations.AddField(
            model_name="order",
            name="goods",
            field=models.ManyToManyField(
                through="orders.OrderGood", to="orders.good", verbose_name="Товары"
            ),
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated_at")),
                ("code", models.CharField(max_length=32, unique=True, verbose_name="Код")),
                (
                    "max_uses_count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимальное количество использований",
                    ),
                ),
                (
                    "current_uses_count",
                    models.PositiveSmallIntegerField(verbose_name="Количество использований"),
                ),
                ("started_at", models.DateTimeField(verbose_name="Начало акции")),
                ("finished_at", models.DateTimeField(verbose_name="Окончание акции")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_codes",
                        to="orders.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="promo_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.promocode",
                verbose_name="Промокод",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("user", "promo_code")},
        ),
    ]
