# Generated by Django 6.0.3 on 2026-03-21 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_promocode_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="used_by",
            field=models.ManyToManyField(
                blank=True, related_name="used_promocodes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
