# Generated by Django 6.0.3 on 2026-03-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_promocode_used_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocode",
            name="used_by",
        ),
    ]
