# Generated by Django 6.0.3 on 2026-03-21 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_promocode_used_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promo_codes",
                to="orders.category",
                verbose_name="Категория",
            ),
        ),
    ]
