# Generated by Django 6.0.3 on 2026-03-22 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_promocode_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordergood",
            name="promo_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promo_codes",
                to="orders.category",
                verbose_name="Категория",
            ),
        ),
    ]
