# Generated by Django 6.0.3 on 2026-03-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_ordergood_promo_applied_alter_promocode_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergood",
            name="promo_applied",
            field=models.BooleanField(default=False, verbose_name="Промокод применен"),
        ),
    ]
