# Generated by Django 6.0.3 on 2026-03-22 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_ordergood_promo_applied"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordergood",
            name="discount_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Процент скидки",
            ),
            preserve_default=False,
        ),
    ]
