# Generated by Django 6.0.3 on 2026-03-23 20:57

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_ordergood_discount_percent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordergood",
            name="promo_applied",
        ),
        migrations.AddField(
            model_name="ordergood",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default="1000.50",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Итоговая сумма",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordergood",
            name="discount_percent",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Процент скидки",
            ),
        ),
    ]
