# Generated by Django 6.0.3 on 2026-03-24 12:32

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_remove_ordergood_promo_applied_ordergood_subtotal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergood",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="Процент скидки",
            ),
        ),
    ]
