# Generated by Django 6.0.3 on 2026-03-24 12:38

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_ordergood_discount_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergood",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="Процент скидки",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="Процент скидки",
            ),
        ),
    ]
