# Generated by Django 6.0.3 on 2026-03-24 12:40

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_ordergood_discount_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergood",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Итоговая сумма",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="Процент скидки",
            ),
        ),
    ]
