# Generated by Django 6.0.3 on 2026-03-24 13:30

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_alter_ordergood_subtotal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_discount_percent",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=4,
                verbose_name="Общий процент скидки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                verbose_name="Сумма до скидки",
            ),
        ),
    ]
