# Generated by Django 6.0.3 on 2026-03-24 13:31

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_total_discount_percent_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=3,
                verbose_name="Общий процент скидки",
            ),
        ),
    ]
