# Generated by Django 6.0.3 on 2026-03-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_alter_order_total_discount_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="current_uses_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Количество использований"
            ),
        ),
    ]
